onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - lefthook

overrides:
  micromatch@<4.0.8: '>=4.0.8'

packages:
  - 'apps/*'
  - 'packages/*'
  - 'docs/*'

catalog:
  '@playwright/test': '1.56.1'
  typescript: '5.9.3'
  eslint: '9.38.0'
